### PR TITLE
Add use_external_pager_for_lsp_document_symbols option

### PR DESCRIPTION
**Pull request by krkhan**
Adding as a workaround for #163

### CODE REVIEW

**Comment by tjdevries** [comment]
You should be able to just pass in an override previewer to the builtin.

Why would we need this setting?

**Comment by krkhan** [comment]
I've tried with both `previewer = previewers.qflist` and `previewer = previewers.bat_maker` in `defaults` of `telescope.setup` and it gives me those raw ANSI escape sequences again. This was the only way I could get it to work, but yes if there's a way of getting it done without a new config value that would be preferable.

**Comment by clason** [comment]
You just need to add back the `-R` flag to https://github.com/nvim-lua/telescope.nvim/blob/6267ead134032b3746488d804b0e09a740d54ab6/lua/telescope/previewers.lua#L33 (which the latest commit already did for line 35, which isn't called for lsp symbols).

**Comment by krkhan** [comment]
gotcha, #172 indeed helps. closing this one

**Pull request closed without merging**
