### PR TITLE
WIP: options menu

### PR DESCRIPTION
**Pull request by sunjon**
WIP finder using options.lua

### CODE REVIEW

**Comment by sunjon** [comment]
wip

**Comment by teto** [comment]
thanks for making a vimmer dream come true

**Comment by teto** [comment]
Does this hide window-scoped options ? I could not find `relativenumber` when typing `relative` in `:Telescope vim_options`

**Comment by tjdevries** [comment]
Yeah, it does curently. It's just options with global scope.

I need to implement some other stuff for this to make sense for setting window options. 

For example... You are not in the window you expect to be in when you are editing. So I will need to track and apply and it can no longer be set from command line. So it is complicated haha

**Comment by tjdevries** [comment]
You can make an issue with info regarding what you want, that'd be helpful for tracking purposes.

**Comment by teto** [comment]
there was this one https://github.com/nvim-lua/telescope.nvim/issues/201. As a first step it could just prefill the command line with 
`:set relativenumber` and let the user press enter so that the correct window gets modified. I understand you want something even more polished so I'll wait, so happy already I will sunset nvim-palette and advise people to use this shiny new telescope.

**Pull request merged**
