### PR TITLE
feat: add buffers

### PR DESCRIPTION
**Pull request by tjdevries**
@Conni2461 Hey, can you check out this PR?

I actually was playing around w/ buffers this morning.

Can you tell me what you think of this?

### CODE REVIEW

**Comment by Conni2461** [comment]
It works great.

Just two little remarks.
Do you want only visible buffers to be listed because you are filtering for loaded buffers? Because neither fzf nor vim-clap do that.

If you have single and multi-digit buffer numbers, the aligning does not fit exactly.

**Comment by tjdevries** [comment]
If I merge this, would you be interested in adding the two features that you've mentioned? We can add an opt for not filtering out the buffers that aren't visible and we can do some text aligning as well.

I'd be happy to help you w/ those PRs if you need anything with it at all.

**Comment by Conni2461** [comment]
Yeah i would be happy to help with that.

**Comment by tjdevries** [comment]
@Conni2461 feel free to submit PR w/ improvements.

**Pull request merged**
