### PR TITLE
feat: add default_icon option

### LINKED ISSUE #177: Option to enable default devicons
Do you think it's a good idea to give the user an option whether or not telescope use the default icon for a filetype that doesn't have an icon? In my case it's `svelte`

nvim-web-devicons has an option to enable the default icon if the icon is not available for that filetype. Personally, I prefer having the default icon rather than having an empty space. Here's a comparison between them, left one is using the default icon and the right one isn't.

Group 38

### PR DESCRIPTION
**Pull request by elianiva**
should resolve #177

### CODE REVIEW

**Comment by tjdevries** [comment]
We should add a way to configure this globally.

Also, do you know if it's possible to do this using nvim devicons directly? Such that we can just pass default = true, and it will do the work for us?

**Comment by tjdevries** [comment]
If we can do it with devicons, we can just add a how to in the Readme and pass default = true where we need to.

**Comment by elianiva** [comment]
It's not currently possible but I've made a [PR](https://github.com/kyazdani42/nvim-web-devicons/pull/16) for devicons that allows you to do that.

**Comment by tjdevries** [comment]
I think it makes sense to enable `default = true` all the time -- since, as you mentioned, it's a bit weird to be missing them.

Does latest commit ( a8e7807 ) work for you? If so, we can close these.

Thanks for the PR :) just ended up implementing this and something else at the same time :laughing:

**Comment by elianiva** [comment]
Epic, it works! Gonna close this and #177

**Pull request closed without merging**
