### PR TITLE
Fix issue with trimming path separator '/' for buffers()

### PR DESCRIPTION
**Pull request by ruifm**
Follow up of https://github.com/nvim-lua/telescope.nvim/pull/104 that introduced a bug in which if `vim.fn.getcwd()` returns a string with a trailing path separator `/`, it causes the bufname path to be wrongly trimmed (e.g. `$(pwd)/foo/bar -> /foo/bar` instead of `$(pwd)/foo/bar -> foo/bar`).

This patch just checks the cwd trailing char and applies an offset.

@tjdevries I'm noticing that so far working with paths in lua has been quite hacky which in turn makes the appearence of these bugs easier. Is there a proper way to work with paths?

I have looked at [plenary.nvim](https://github.com/nvim-lua/plenary.nvim) , and more concretely at  [path.lua](https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/path.lua) which according to the projects README it's suppose to be the equivalent of python's pathlib. But from looking at that file, it's still far behind which leaves me for now with manual string handling.

### CODE REVIEW

**Comment by tjdevries** [comment]
should probably use os_separator, which we've got elsewhere in telescope.

Yes, we should probably be using the `path.lua` from plenary. It is in need of some more features :laughing: 

I also maintain plenary, so if you want to add any features to make path handling easier here, let me know.

**Comment by tjdevries** [comment]
( I just added os sep fix. If you're interested, we can work on improving plenary's `path` module, and then use it here )

**Comment by ruifm** [comment]
> ( I just added os sep fix. If you're interested, we can work on improving plenary's `path` module, and then use it here )

Thanks, it was in my TODO but it was just a busy week and it got buried in my GH notifications. I am interested, will look into it and start making some PR's that implement pathlib equivalents.

**Comment by tjdevries** [comment]
Also, we should use libuvs stuff for access file system, not  viml wrappers like I had before. Can explain more later.

**Pull request merged**
