### PR TITLE
feat: Add dropdown layout strategy

### PR DESCRIPTION
**Pull request by rockerBOO**
Adds a dropdown strategy.

Adds results_title and preview_title options.

```vim
nnoremap <Leader>f <cmd>:lua require'telescope.builtin'.find_files({ sorting_strategy = "ascending", preview_cutoff = 200,border = false, layout_strategy = "dropdown", prompt = "",
width = 50,winblend = 3, results_title = "", borderchars = { '', '', '', '', '', '', '', ''} })<CR>
```

https://clips.twitch.tv/ExpensiveExquisitePigeonVoHiYo

### CODE REVIEW

**Comment by rockerBOO** [comment]
Right now I can't hide the preview and it leaves a box on the top left.

**Comment by rockerBOO** [comment]
Also its called dropdown but you need to set the sorting_strategy to get it to work right. 

That may be part of the "theme" abstraction.

**Comment by tjdevries** [comment]
This is ready for me to review?

I may push some ideas for easier config, but I could always update these after I implement them, unless you wanted to. 

I like the idea of "themes".

**Comment by rockerBOO** [comment]
Closing in favor of #79

**Pull request closed without merging**
