### PR TITLE
refactor: prompt->prompt_title ; prompt_prefix->prompt_text

### PR DESCRIPTION
**Pull request by pwntester**
Refactoring `prompt` to `prompt_title` which is consistent with `results_title` and `previewer_title` and `prompt_prefix` to `prompt_text`

### CODE REVIEW

**Comment by tami5** [comment]
perhaps instead of prefix_text, prefix_header makes more sense, and the same goes for result.

**Comment by pwntester** [comment]
> I think I prefer to keep it prompt prefix.
> 
> 
Should we keep the `prompt` to `prompt_title` change though?

**Comment by tjdevries** [comment]
Yeah, prompt to prompt title is good.

**Comment by pwntester** [comment]
ok, should be good to go

**Comment by pwntester** [comment]
@tjdevries Can we merge this now?

**Pull request merged**
